### PR TITLE
updating contributing guidelines and the site yaml for new branch

### PR DESCRIPTION
**Pull request by Preeticp**

### CODE REVIEW

**Comment by Preeticp** [comment]
@joaedwar please review the contributing guidelines.

**Comment by Preeticp** [comment]
Fixes issue #77

**Review by nebelsprachen — APPROVED** [review]
LGTM. I think we can remove the previous contribution info ( i.e. contribute with markdown)

**Comment by Preeticp** [comment]
Fixed Joan. Going ahead and merging this.

**Pull request merged**
